apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.component }}
  labels:
    component: {{ .Values.component }}
spec:
  containers:
    - name: nginx
      image: 581798224530.dkr.ecr.us-east-1.amazonaws.com/nginx_practise
