apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.component }}
spec:
  type: NodePort
  selector:
    component: {{ .Values.component }}
  ports:
    - port: 80
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
